# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Year',
        ),
    ]
