# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_delete_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.PositiveIntegerField(default=2017)),
            ],
        ),
    ]
