# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='financial_year',
            field=models.CharField(max_length=200),
        ),
    ]
