# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20170518_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='year',
            field=models.PositiveIntegerField(default=2017),
        ),
    ]
