# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_district_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='district',
            old_name='name',
            new_name='District_name',
        ),
        migrations.AddField(
            model_name='project',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='landing.District'),
        ),
        migrations.AddField(
            model_name='project',
            name='fin_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financialyear', to='landing.Year'),
        ),
    ]
