# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_auto_20170518_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='year',
        ),
    ]
