# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_remove_year_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('CO', 'Completed'), ('OG', 'Ongoing'), ('ST', 'Stalled'), ('FR', 'Future')], default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='project',
            name='district',
        ),
        migrations.AddField(
            model_name='project',
            name='district',
            field=models.ManyToManyField(blank=True, related_name='Districts', to='landing.District'),
        ),
    ]
