# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_auto_20170518_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Approved', models.PositiveIntegerField(default=0)),
                ('Estimates', models.PositiveIntegerField(default=0)),
                ('Actual', models.PositiveIntegerField(default=0)),
                ('fin_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_years', to='landing.Year')),
            ],
        ),
    ]
