# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='BudgetItem',
            field=models.CharField(default='', max_length=200),
        ),
    ]
