# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0018_budget_budgetcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='fin_year',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
