# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0020_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BudgetItem', models.CharField(default='', max_length=200)),
                ('BudgetCategory', multiselectfield.db.fields.MultiSelectField(choices=[(1, ''), (2, 'Petrol'), (3, 'Stationary'), (4, 'Allowances')], default=1, max_length=7)),
                ('Approved', models.PositiveIntegerField(default=0)),
                ('Estimates', models.PositiveIntegerField(default=0)),
                ('Actual', models.PositiveIntegerField(default=0)),
                ('fin_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_years', to='landing.Year')),
            ],
        ),
    ]
