# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0021_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
