# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0022_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='BudgetCategory',
            field=models.CharField(choices=[(1, ''), (2, 'Petrol'), (3, 'Stationary'), (4, 'Allowances')], default='', max_length=200),
        ),
    ]
