# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_person'),
        ('landing', '0025_auto_20170526_1141'),
    ]

    operations = [
    ]
