# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0026_merge_20170531_0948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
