# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0027_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='BudgetCategory',
        ),
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.CharField(choices=[('JULY', 'july'), ('AUGUST', 'august'), ('SEPTEMBER', 'september'), ('OCTOBER', 'october'), ('NOVEMBER', 'november'), ('DECEMBER', 'december'), ('JANUARY', 'january'), ('FEBRUARY', 'february'), ('MARCH', 'march'), ('APRIL', 'april'), ('MAY', 'may'), ('JUNE', 'june')], default='JULY', max_length=200),
        ),
    ]
