# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0028_auto_20170605_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='Actual',
            new_name='AprilActual',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='month',
        ),
        migrations.AddField(
            model_name='budget',
            name='AugustActual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budget',
            name='DecemberActual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budget',
            name='FebruaryActual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budget',
            name='JanuaryActual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budget',
            name='JulyActual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budget',
            name='JuneActual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budget',
            name='MarchActual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budget',
            name='MayActual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budget',
            name='NovemberActual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budget',
            name='OctoberActual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budget',
            name='SeptemberActual',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
