# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0029_auto_20170607_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='AprilActual',
            new_name='April',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='AugustActual',
            new_name='August',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='DecemberActual',
            new_name='December',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='FebruaryActual',
            new_name='February',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='JanuaryActual',
            new_name='January',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='JulyActual',
            new_name='July',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='JuneActual',
            new_name='June',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='MarchActual',
            new_name='March',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='MayActual',
            new_name='May',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='NovemberActual',
            new_name='November',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='OctoberActual',
            new_name='October',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='SeptemberActual',
            new_name='September',
        ),
    ]
