# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0030_auto_20170607_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='Approved',
            field=models.PositiveIntegerField(default=0, help_text='Enter a figure, excluding commas'),
        ),
    ]
